### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by sebastienbeau** [akretion/voodoo-template#12]
We should split the voodoo project into 3 parts
1- host cli
2- voodoo templating
3- guest cli

1- host cli
We can use fig for this. We may need to modify fig in order to add plugin (Indeed we may need some extra command for odoo)

2- voodoo templating
We must create a list of buildout template for our project, in order to start then quickly (we can share then with other partner, this may not depend of odoo)

3- guest cli
We can create a guest cli in order to simplify the buildout commande and to integrate extra commande
list of possible commande
ak build
ak run
ak freeze
ak db backup
ak db load
...

**Comment by rvalyi** [comment]
done long ago so closing this
