### ISSUE TITLE
asciiart is displayed twice now

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo-template#15]
whe doing voodoo run

**Comment by sebastienbeau** [comment]
In fact no sure it's the best way to do it. Indeed with that option the message is not display when running voodoo open. Maybe we should understand why bash is call twice at the start

**Comment by rvalyi** [comment]
Hum voodoo open is really cool! I didn't know you could do that. Well I prefer the situation now than before but you are right, it could be improve further by getting at the root of the problem. That being said improving this is not a top priority for me now...
